import mongoose from "mongoose";

const questionSchema = new mongoose.Schema(
  {
    q: { type: String, required: true },
    a: String, // model answer generated by AI
    userAnswer: String, // filled when user does mock Q&A
    score: {
      // 0-1, scored when user submits answer
      type: Number,
      min: 0,
      max: 1,
      default: null,
    },
    feedback: String, // what to improve in the answer
    category: {
      // what type of question this is
      type: String,
      enum: ["technical", "behavioral", "situational", "role-specific"],
      default: "technical",
    },
  },
  { _id: false },
);

const prepSessionSchema = new mongoose.Schema(
  {
    applicationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Application",
      required: true,
      index: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    questions: [questionSchema],

    // summary after mock session
    weakPoints: [String], // questions with score < 0.6
    strongPoints: [String], // questions with score > 0.8
    avgScore: {
      type: Number,
      min: 0,
      max: 1,
      default: null,
    },

    // session state
    status: {
      type: String,
      enum: ["generated", "in_progress", "completed"],
      default: "generated",
    },
  },
  { timestamps: true },
);

prepSessionSchema.index(
  {
    applicationId: 1,
    userId: 1,
  },
  {
    unique: true,
  },
);

export const PrepSession = mongoose.model("PrepSession", prepSessionSchema);
